LIBRARY=lib/libtbusapi.a
TARGET=$(LIBRARY)
HOME=../
CINC=-I/usr/local/tlibc/include/ -Iinclude -I$(HOME)/tcommon/include -I$(HOME)/tbus/include/

CFILE=$(wildcard source/*.c)

include $(HOME)/build.mk
